from typing import Protocol
from uuid import UUID

from app.modules.catalog.application.dtos import PublicProduct
from app.modules.favorites.domain.models import Favorite


class FavoriteRepository(Protocol):
    async def list_favorites(
        self, user_id: UUID, limit: int, offset: int
    ) -> list[Favorite]: ...
    async def add_favorite(self, user_id: UUID, product_id: UUID) -> Favorite: ...
    async def remove_favorite(self, user_id: UUID, product_id: UUID) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class FavoriteCatalog(Protocol):
    async def product_exists(self, product_id: UUID) -> bool: ...
    async def products(
        self, branch_id: UUID, product_ids: tuple[UUID, ...]
    ) -> dict[UUID, PublicProduct]: ...
