from typing import Protocol
from uuid import UUID


class BranchAdministrationRepository(Protocol):
    async def list_branches(
        self, user_id: UUID, limit: int, offset: int
    ) -> list[dict]: ...
    async def get_branch(
        self, branch_id: UUID, *, lock: bool = False
    ) -> dict | None: ...
    async def create_branch(self, values: dict) -> dict: ...
    async def update_branch(self, branch_id: UUID, values: dict) -> dict: ...
    async def replace_hours(self, branch_id: UUID, hours: list[dict]) -> list[dict]: ...
    async def deactivate_branch(self, branch_id: UUID) -> None: ...
    async def assign_creator(self, branch_id: UUID, user_id: UUID) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class BranchOrderConfiguration(Protocol):
    async def initialize(self, branch_id: UUID, timezone: str) -> None: ...
    async def synchronize_timezone(self, branch_id: UUID, timezone: str) -> None: ...
    async def has_active_operations(self, branch_id: UUID) -> bool: ...


class BranchTimezoneSynchronization(Protocol):
    async def synchronize_timezone(self, branch_id: UUID, timezone: str) -> None:
        """Synchronize a validated clock while the caller holds Branch UPDATE."""
        ...
