import io
import re

from alembic import command
from alembic.script import ScriptDirectory
from sqlalchemy import Numeric
from sqlmodel import SQLModel

from app.modules.orders.infrastructure.persistence import models as order_models
from tests.test_phase1_foundation import EXPECTED_PHASE_ONE_TABLES
from tests.test_phase1_migration import migration_config
from tests.test_phase2_migration import EXPECTED_PHASE_TWO_TABLES
from tests.test_phase3_migration import EXPECTED_PHASE_THREE_TABLES

EXPECTED_PHASE_FOUR_TABLES = {
    "orders",
    "order_items",
    "order_item_addon_options",
    "order_status_history",
    "order_local_details",
    "order_pickup_details",
    "order_delivery_details",
    "restaurant_tables",
    "branch_order_settings",
    "delivery_zones",
    "order_schedule_calculations",
}


def test_phase4_metadata_has_only_eleven_new_tables_with_decimal_money():
    assert order_models
    assert set(SQLModel.metadata.tables) == (
        EXPECTED_PHASE_ONE_TABLES
        | EXPECTED_PHASE_TWO_TABLES
        | EXPECTED_PHASE_THREE_TABLES
        | EXPECTED_PHASE_FOUR_TABLES
    )
    for name in EXPECTED_PHASE_FOUR_TABLES:
        for column in SQLModel.metadata.tables[name].columns:
            if any(
                word in column.name
                for word in ("price", "total", "fee", "minimum_order")
            ):
                assert isinstance(column.type, Numeric) and column.type.asdecimal
                assert (column.type.precision, column.type.scale) == (18, 2)
    identity = SQLModel.metadata.tables["orders"].c.order_number.identity
    assert identity is not None and identity.start == 1
    assert (
        SQLModel.metadata.tables["delivery_zones"].c.district.type.__class__.__name__
        == "CITEXT"
    )


def test_one_linear_head_and_prior_revisions_preserved():
    scripts = ScriptDirectory.from_config(migration_config())
    assert scripts.get_heads() == ["0004_orders"]
    assert scripts.get_revision("0004_orders").down_revision == "0003_cart"
    assert scripts.get_revision("0003_cart").down_revision == "0002_catalog"
    assert scripts.get_revision("0002_catalog").down_revision == "0001_phase1"


def test_offline_upgrade_is_scoped_and_contains_race_barriers_and_seeds():
    output = io.StringIO()
    command.upgrade(migration_config(output), "0003_cart:0004_orders", sql=True)
    sql = output.getvalue()
    assert set(re.findall(r"CREATE TABLE (\w+)", sql)) == EXPECTED_PHASE_FOUR_TABLES
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql
    assert (
        "UNIQUE (source_cart_id)" in sql
        and "UNIQUE (customer_id, idempotency_key)" in sql
    )
    assert (
        "CHECKED_OUT" in sql
        and "ALTER TABLE carts DROP CONSTRAINT ck_carts_status" in sql
    )
    assert "total = subtotal + charges_total - discount_total" in sql
    assert "line_total_snapshot = unit_price_snapshot * quantity" in sql
    assert "ON DELETE SET NULL" in sql and "ON DELETE RESTRICT" in sql
    assert all(
        district in sql for district in ("Tarapoto", "Morales", "La Banda de Shilcayo")
    )
    assert "ORDER_SETTINGS_MANAGE" in sql and "ORDER_MANAGE" in sql
    assert sql.count("restaurant_phase1_set_updated_at()") == 4
    assert (
        "CREATE EXTENSION" not in sql
        and "CREATE FUNCTION" not in sql
        and "CREATE TABLE payments" not in sql
    )


def test_offline_downgrade_refuses_checked_out_data_before_dropping_phase4_only():
    output = io.StringIO()
    command.downgrade(migration_config(output), "0004_orders:0003_cart", sql=True)
    sql = output.getvalue()
    assert set(re.findall(r"DROP TABLE (\w+)", sql)) == EXPECTED_PHASE_FOUR_TABLES
    assert sql.index("RAISE EXCEPTION") < sql.index("DROP TABLE")
    assert "status IN ('ACTIVE', 'ABANDONED')" in sql
    assert (
        "DROP FUNCTION" not in sql
        and "DROP TABLE carts" not in sql
        and "DROP TABLE products" not in sql
    )


def test_fk_snapshot_delete_policies_and_no_table_uniqueness():
    table = SQLModel.metadata.tables["order_delivery_details"]
    assert next(iter(table.c.customer_address_id.foreign_keys)).ondelete == "SET NULL"
    assert next(iter(table.c.delivery_zone_id.foreign_keys)).ondelete == "RESTRICT"
    local = SQLModel.metadata.tables["order_local_details"]
    assert not local.c.restaurant_table_id.unique
    orders = SQLModel.metadata.tables["orders"]
    constraints = {constraint.name for constraint in orders.constraints}
    assert {
        "uq_orders_source_cart",
        "uq_orders_customer_idempotency",
        "ck_orders_totals",
    } <= constraints
