from typing import Protocol
from uuid import UUID

from app.modules.catalog.application.dtos import (
    AddonCreate,
    BranchProductConfig,
    CatalogChanges,
    CategoryCreate,
    ImageCreate,
    OptionCreate,
    PresentationCreate,
    ProductAggregate,
    ProductCreate,
)
from app.modules.catalog.domain.models import (
    BranchProduct,
    Category,
    Product,
    ProductAddon,
    ProductAddonOption,
    ProductImage,
    ProductPresentation,
)


class CatalogAuthorization(Protocol):
    async def can_manage(self, user_id: UUID, branch_id: UUID | None) -> bool: ...


class CatalogRepository(Protocol):
    async def branch_is_active(self, branch_id: UUID) -> bool: ...
    async def public_products(
        self,
        branch_id: UUID,
        product_id: UUID | None = None,
        *,
        product_ids: tuple[UUID, ...] | None = None,
    ) -> list[ProductAggregate]: ...
    async def admin_product(self, product_id: UUID) -> ProductAggregate | None: ...
    async def list_categories(self) -> list[Category]: ...
    async def list_products(self) -> list[Product]: ...
    async def get_category(
        self, category_id: UUID, *, lock: bool = False
    ) -> Category | None: ...
    async def get_product(
        self, product_id: UUID, *, lock: bool = False
    ) -> Product | None: ...
    async def category_has_active_products(self, category_id: UUID) -> bool: ...
    async def create_category(self, command: CategoryCreate) -> Category: ...
    async def update_category(
        self, category: Category, changes: CatalogChanges
    ) -> Category: ...
    async def archive_category(self, category: Category) -> Category: ...
    async def create_product(self, command: ProductCreate) -> Product: ...
    async def update_product(
        self, product: Product, changes: CatalogChanges
    ) -> Product: ...
    async def archive_product(self, product: Product) -> Product: ...
    async def get_image(
        self, product_id: UUID, image_id: UUID
    ) -> ProductImage | None: ...
    async def create_image(
        self, product_id: UUID, command: ImageCreate
    ) -> ProductImage: ...
    async def update_image(
        self, image: ProductImage, changes: CatalogChanges
    ) -> ProductImage: ...
    async def archive_image(self, image: ProductImage) -> ProductImage: ...
    async def get_presentation(
        self, product_id: UUID, presentation_id: UUID
    ) -> ProductPresentation | None: ...
    async def create_presentation(
        self, product_id: UUID, command: PresentationCreate
    ) -> ProductPresentation: ...
    async def update_presentation(
        self, presentation: ProductPresentation, changes: CatalogChanges
    ) -> ProductPresentation: ...
    async def archive_presentation(
        self, presentation: ProductPresentation
    ) -> ProductPresentation: ...
    async def get_addon(
        self, product_id: UUID, addon_id: UUID
    ) -> ProductAddon | None: ...
    async def create_addon(
        self, product_id: UUID, command: AddonCreate
    ) -> ProductAddon: ...
    async def update_addon(
        self, addon: ProductAddon, changes: CatalogChanges
    ) -> ProductAddon: ...
    async def archive_addon(self, addon: ProductAddon) -> ProductAddon: ...
    async def get_option(
        self, addon_id: UUID, option_id: UUID
    ) -> ProductAddonOption | None: ...
    async def create_option(
        self, addon_id: UUID, command: OptionCreate
    ) -> ProductAddonOption: ...
    async def update_option(
        self, option: ProductAddonOption, changes: CatalogChanges
    ) -> ProductAddonOption: ...
    async def archive_option(
        self, option: ProductAddonOption
    ) -> ProductAddonOption: ...
    async def get_branch_product(
        self, branch_id: UUID, product_id: UUID
    ) -> BranchProduct | None: ...
    async def upsert_branch_product(
        self, branch_id: UUID, product_id: UUID, command: BranchProductConfig
    ) -> BranchProduct: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
