from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.modules.cart.domain.models import Cart
from app.modules.orders.application.dtos import (
    AddressSnapshot,
    BranchHours,
    CustomerSnapshot,
    PreparationEstimate,
)
from app.modules.orders.domain.models import (
    BranchOrderSettings,
    DeliveryZone,
    Order,
    OrderItem,
    RestaurantTable,
    StatusHistory,
)


class CartCheckoutGateway(Protocol):
    async def get_and_lock_active_cart(self, customer_id: UUID) -> Cart | None: ...
    async def has_checked_out_cart(self, customer_id: UUID) -> bool: ...
    async def validate_for_checkout(self, cart: Cart) -> tuple[OrderItem, ...]: ...
    async def mark_checked_out(self, cart: Cart) -> None: ...


class CustomerCheckoutGateway(Protocol):
    async def lock_customer(self, customer_id: UUID) -> CustomerSnapshot | None: ...
    async def address(
        self, customer_id: UUID, address_id: UUID
    ) -> AddressSnapshot | None: ...


class OrderAuthorization(Protocol):
    async def has_permission(
        self, user_id: UUID, branch_id: UUID, permission: str
    ) -> bool: ...


class KitchenLoadEstimator(Protocol):
    async def estimate(
        self, branch_id: UUID, settings: BranchOrderSettings
    ) -> PreparationEstimate: ...


class OrderRepository(Protocol):
    async def pickup_due_for_release(
        self, now: datetime, limit: int = 100
    ) -> list[Order]: ...
    async def by_idempotency(self, customer_id: UUID, key: str) -> Order | None: ...
    async def get_owned(self, customer_id: UUID, order_id: UUID) -> Order | None: ...
    async def list_owned(
        self, customer_id: UUID, limit: int, offset: int
    ) -> list[Order]: ...
    async def create(self, order: Order) -> Order: ...
    async def lock_order(self, order_id: UUID) -> Order | None: ...
    async def release_cash(self, order: Order, history: StatusHistory) -> Order: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class OrderSettingsRepository(Protocol):
    async def branch_is_active(self, branch_id: UUID) -> bool: ...
    async def get_settings(
        self, branch_id: UUID, *, lock: bool = False, for_update: bool = False
    ) -> BranchOrderSettings: ...
    async def save_settings(
        self, settings: BranchOrderSettings
    ) -> BranchOrderSettings: ...
    async def branch_hours(self, branch_id: UUID) -> BranchHours: ...
    async def table_by_qr(self, qr_token: UUID) -> RestaurantTable | None: ...
    async def list_tables(self, branch_id: UUID) -> list[RestaurantTable]: ...
    async def get_table(
        self, branch_id: UUID, table_id: UUID
    ) -> RestaurantTable | None: ...
    async def save_table(self, table: RestaurantTable) -> RestaurantTable: ...
    async def resolve_zone(
        self, branch_id: UUID, district: str
    ) -> DeliveryZone | None: ...
    async def list_zones(self, branch_id: UUID) -> list[DeliveryZone]: ...
    async def get_zone(self, branch_id: UUID, zone_id: UUID) -> DeliveryZone | None: ...
    async def save_zone(self, zone: DeliveryZone) -> DeliveryZone: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
