"""Shared deterministic API contract and route checks (no DB connection)."""

from collections import Counter

from fastapi.routing import APIRoute

from app.factory import create_app
from app.shared.infrastructure.config.settings import Settings

PUBLIC_OPERATIONS = frozenset(
    {
        ("GET", "/"),
        ("GET", "/health"),
        ("GET", "/api/v1/health"),
        ("GET", "/api/v1/health/ready"),
        ("POST", "/api/v1/auth/otp/request"),
        ("POST", "/api/v1/auth/otp/verify"),
        ("POST", "/api/v1/auth/register"),
        ("POST", "/api/v1/auth/guest"),
        ("POST", "/api/v1/auth/login"),
        ("POST", "/api/v1/auth/refresh"),
        ("POST", "/api/v1/auth/logout"),
        ("GET", "/api/v1/branches"),
        ("GET", "/api/v1/branches/{branch_id}"),
        ("GET", "/api/v1/catalog/menu"),
        ("GET", "/api/v1/catalog/products/{product_id}"),
    }
)
VERIFIED_WEBHOOKS = frozenset(
    {
        ("POST", "/api/v1/payments/webhooks/{provider_code}"),
        ("POST", "/api/v1/payments/refund-webhooks/{provider_code}"),
    }
)
HTTP_METHODS = frozenset({"get", "post", "put", "patch", "delete", "options", "head"})
FORBIDDEN_SEGMENTS = frozenset(
    {
        "debug",
        "test",
        "fake",
        "simulate-payment",
        "simulate-refund",
        "simulate-push",
        "mark-paid",
        "mark-refunded",
    }
)


def contract_app():
    # Explicit DEFAULT inputs for EVERY field avoid .env/deployment env access.
    defaults = {
        name: field.get_default(call_default_factory=True)
        for name, field in Settings.model_fields.items()
    }
    defaults.update(app_env="test", app_debug=False)
    return create_app(Settings(_env_file=None, **defaults))


def api_routes(application):
    for route in application.routes:
        if isinstance(route, APIRoute):
            yield route
        elif hasattr(route, "effective_route_contexts"):
            # FastAPI 0.142's lazy includes already flatten nested route contexts.
            yield from route.effective_route_contexts()


def route_policy(method, path, operation):
    key = method.upper(), path
    if key in PUBLIC_OPERATIONS:
        return "public (proof/refresh token where required)"
    if key in VERIFIED_WEBHOOKS:
        return "verified provider webhook, fail closed"
    if operation.get("security"):
        if "/admin/" in path:
            return "registered + DB permission/branch scope"
        if "/kitchen/" in path:
            return "registered + KITCHEN_VIEW/MANAGE + branch scope"
        return "Bearer + current DB identity/ownership"
    raise ValueError(f"Undeclared route policy: {method} {path}")


def validate_contract(application, schema):
    errors = []
    routes = list(api_routes(application))
    pairs = Counter(
        (method, route.path) for route in routes for method in route.methods
    )
    errors.extend(
        f"Duplicate route: {pair}" for pair, count in pairs.items() if count > 1
    )
    ids = []
    for path, methods in schema["paths"].items():
        if FORBIDDEN_SEGMENTS.intersection(path.split("/")):
            errors.append(f"Forbidden route: {path}")
        for method, operation in methods.items():
            if method not in HTTP_METHODS:
                continue
            ids.append(operation.get("operationId"))
            try:
                route_policy(method, path, operation)
            except ValueError as error:
                errors.append(str(error))
            if path.endswith("/stream"):
                if "text/event-stream" not in operation["responses"]["200"].get(
                    "content", {}
                ):
                    errors.append(f"Missing SSE contract: {path}")
    if None in ids or len(ids) != len(set(ids)):
        errors.append("Missing or duplicate operationId")
    bearer = schema["components"]["securitySchemes"].get("HTTPBearer", {})
    if bearer != {"type": "http", "scheme": "bearer"}:
        errors.append("HTTPBearer scheme missing")
    return errors


def inventory(application, schema):
    lines = [
        "# API inventory",
        "",
        "Generated by `scripts/export_openapi.py`; do not edit by hand.",
        "",
        "| Method | Path | Tags | Policy | Module |",
        "|---|---|---|---|---|",
    ]
    for route in sorted(api_routes(application), key=lambda r: r.path):
        for method in sorted(route.methods):
            operation = schema["paths"].get(route.path, {}).get(method.lower(), {})
            policy = route_policy(method, route.path, operation)
            module = route.endpoint.__module__
            lines.append(
                f"| {method} | `{route.path}` | {', '.join(route.tags)} "
                f"| {policy} | `{module}` |"
            )
    return "\n".join(lines) + "\n"
